language: osx
#rvm:
# - 2018.3.3 
# - salt
# safelist
branches:
  only:
  - master
  - salt

matrix:
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile.rails-2.3.x
    env: ISOLATED=true
  - rvm: jruby
    gemfile: gemfiles/Gemfile.rails-2.3.x
    env: ISOLATED=true
